# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCSWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCSWeather
  pod 'EasyPeasy'
  pod 'RxSwift'
  pod 'Moya'
  pod 'Moya-ModelMapper'
  pod 'RxFlow'
  pod 'NSObject+Rx'
  pod 'Swinject'

  target 'TCSWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
